name: Publish JavaDoc to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write  # required for pushing to gh-pages

jobs:
  build-and-publish-javadoc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build JavaDoc
        run: ./mvnw -B -ntp -DskipTests javadoc:javadoc

      - name: Publish to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./target/site/apidocs
          force_orphan: true
          commit_message: "docs: publish JavaDoc (auto)"
